### ISSUE TITLE
[kubemod] The CRD is not valid

### ISSUE THREAD

**Issue by machine424** [kubemod/kubemod-helm#11]
Hello,

In https://github.com/kubemod/kubemod-helm/pull/10/files the CRD in `helm-chart/kubemod/crds` was superficially upgraded to v1. The manifest needs to be adapted (see [here](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122) for details).

Could we consider the CustomResourceDefinition in https://github.com/kubemod/kubemod/blob/master/bundle.yaml as source of truth and sync from it?

**Comment by vassilvk** [comment]
Hi @machine424,

Using the original resource definitions from `kubemod` makes sense. That said, the actual source of truth is not `bundle.yaml` - the bundle is a product of running a `kustomize` build against the original resource definitions which are located in `kubemod`'s `config` folder (https://github.com/kubemod/kubemod/tree/master/config).

Kubemod's `Makefile` includes a target called `bundle` which invokes `kustomize` to build `bundle.yaml` (https://github.com/kubemod/kubemod/blob/master/Makefile#L45).

I think it would be best if we had another `Makefile` target, say `helm`, which produces the `templates` folder for the helm chart, using the original resource definitions from `kubemod/config`.

@desaintmartin, thoughts?

**Comment by machine424** [comment]
Thanks for your response.

My mistake, wrong link, I meant the definition in here https://github.com/kubemod/kubemod/blob/master/config/crd/bases/api.kubemod.io_modrules.yaml generated by the target `manifests`, I wanted to know if it is always up-to-date.

I don't think we need to generate the helm chart's `templates` folder, all we need is the CRD.

Edit: So we can use https://github.com/kubemod/kubemod/blob/master/config/crd/bases/api.kubemod.io_modrules.yaml to fill/sync the chart's `crds/`

**Comment by vassilvk** [comment]
Yes, this makes sense.
Since manifests are generated at every release of `kubemod`, this file is always up to date at the corresponding release tag.

**Comment by vassilvk** [comment]
@machine424, please feel free to submit a PR.

**Comment by machine424** [comment]
Here you go https://github.com/kubemod/kubemod-helm/pull/12

**Comment by vassilvk** [comment]
Closed by #12

**Comment by vassilvk** [comment]
Thanks @machine424 !
