### ISSUE TITLE
Job Image Not Templated

### ISSUE THREAD

**Issue by lewis-strong** [kubemod/kubemod-helm#23]
Helm values contains an input for the Kubemod CRT image but these are not used as part of templating and are set as fixed values

[Input Values](https://github.com/kubemod/kubemod-helm/blob/main/helm-chart/kubemod/values.yaml#L12C1-L16C18)

[Example Fixed Manifest Values](https://github.com/kubemod/kubemod-helm/blob/main/helm-chart/kubemod/templates/job-crt/job-crt.yaml#L19)

These values should be templated.

**Comment by vassilvk** [comment]
Resolved by https://github.com/kubemod/kubemod-helm/pull/24
