### ISSUE TITLE
Deprecated CRD API version

### ISSUE THREAD

**Issue by vassilvk** [kubemod/kubemod-helm#9]
When installing the Helm chart on Kubernetes 1.16+ (for example Kubernetes 1.22) the following warning is issued:
`W0906 17:35:07.323205    6568 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition`

This issue was fixed in KubeMod's manifests: see https://github.com/kubemod/kubemod/issues/65

The same fix should be applied to the manifests carried with the Helm chart.

**Comment by gclawes** [comment]
+1 on this.  The helm chart does not work on recent versions of k3s, which has deprecated APIs removed.
